### ISSUE TITLE
error Connecting 

### ISSUE THREAD

**Issue by huscvarna** [NanMetal/Claymore-No-Fee-Proxy#1]
Hi there, Need you help with this issue. I have the Proxy up and running and the client connects and i get the message from the proxy getting the connection
My command on the proxy is: {
    "local_host": "192.168.1.96:8080",  
    "pool_address": "pool.supportxmr.com:9000",
    "wallet": "myaddress that i removed",

    "ssl": true}
I have changes the port from the local host port for many others. The Pool only lets me use the 9000 port, the 7777 gives me auth error. 

On the client side this is my command:
setx GPU_MAX_ALLOC_PERCENT 100
NsGpuCNMiner.exe  -o stratum+tcp://192.168.1.96:8080 -u mywalletthatiremoved -p miner1 -allpools 1 -mport 0

![image](https://user-images.githubusercontent.com/34287997/33798937-b91a4750-dd19-11e7-8b69-1baeb4ff0057.png)

On the client side this is my command:
setx GPU_MAX_ALLOC_PERCENT 100
NsGpuCNMiner.exe  -o stratum+tcp://192.168.1.96:8080 -u mywalletthatiremoved -p miner1 -allpools 1 -mport 0

Now without the -allpools 1 
The Proxy gets the devshare
![image](https://user-images.githubusercontent.com/34287997/33798979-8ca90840-dd1a-11e7-84c7-31ab3222984c.png)

But on the client side (that i removed the allpools option).

![image](https://user-images.githubusercontent.com/34287997/33798986-af6d3e6e-dd1a-11e7-82f4-9af2adf7083c.png)

I tried already a lot of options but it seams that its because of detecting the deveshare and not beeing able to forward it to the Pool.

**Comment by NanMetal** [comment]
I just spent the day trying to fix this, just published a [new version](https://github.com/NanMetal/Claymore-CryptoNote-Proxy/releases/tag/v1.5)
I got it working with the ports 9000, 443 and 80 (non ssl), it seems to work fine. Try it and tell me how it goes

**Comment by huscvarna** [comment]
Hi NanMetal 
Yes its working, but now Claymore says this 
![image](https://user-images.githubusercontent.com/34287997/33808297-c7abdf5a-dddb-11e7-8d28-e6b73def4af7.png)
:(
Is there a way to bypass this? (didn´t change nothing on the configs. Im using another computer on a different router has proxy and he detects it wrong :( ) 
And send me your XMR wallet so i can send you some love for your job.

**Comment by NanMetal** [comment]
It's because claymore checks if the IP starts with 192.168... (local IP ranges). If you dont care about having a static ip and running the proxy in the same computer as the miner, you can try this:
https://github.com/NanMetal/Claymore-CryptoNote-Proxy/wiki/Add-a-custom-IP-and-host-name
And then you can use that IP or hostname in the claymore config and the proxy "local_host" value
If you don't know what to put in your static ip check google how to and do step 5 onwards.

**Comment by huscvarna** [comment]
Or i can change the Router IP DHCP scope probably easy.
This why i want to remove the DevFee look at this? they take more than they say on the Read me
![image](https://user-images.githubusercontent.com/34287997/33808528-fe2d3da4-dddf-11e7-9b1a-ab8351ff0576.png)

**Comment by NanMetal** [comment]
Yeah that's what I noticed when I created this, sometimes is less, sometimes is A LOT more. I'm glad that it's working for you!

**Comment by huscvarna** [comment]
Can you send me you wallet address so I can send you some xmr for your work?

**Comment by NanMetal** [comment]
48Ba1QniibJ34Di57C96M58Gq5EQ7ixuUNxcwnfe8zeCgy8UjCZWf4NAQW5P3iuE8EYc3MkA7DQ9USWDmijbN7b9HPZVTb8
Thank you for that!

**Comment by huscvarna** [comment]
Done :) not mutch but you deserve it
