### ISSUE TITLE
Help for setting up your proxy

### ISSUE THREAD

**Issue by QuentinHK0** [NanMetal/Claymore-No-Fee-Proxy#2]
Hello,
First of all thank you for your work :) , I try to set up your proxy (Ver 1.4.0) with Claymore (Claymore.CryptoNote.GPU.Miner.v9.7.Beta.-.POOL).

This is my host file :
194.1.1.10 xmr.cryptofake.fr

My proxy conf file :
{ "local_host": "xmr.cryptofake.fr:8888", "pool_address": "xmr.crypto-pool.fr:8443", "wallet": "<MywalletAdress>", "worker": "", "ssl": true }

My start.bat for Claymore :
setx GPU_MAX_ALLOC_PERCENT 100 NsGpuCNMiner.exe -o stratum+tcp://xmr.cryptofake.fr:8888 -u <MywalletAdress> X -p x

Claymore return this :
https://i.imgur.com/duSv6gh.jpg

I certainly made a mistake but I do not see where.
Thank's for helping.

**Comment by NanMetal** [comment]
Try the last version. I can't try that pool at the moment. I will check when I get back from work

**Comment by QuentinHK0** [comment]
Hi 
Thank you for your reply, i try with the last version. same issue.

**Comment by NanMetal** [comment]
I checked and is working fine with the 1.5 version. Try putting the wallet address alone in "wallet" (proxy.txt) and the same in claymore (do not add worker name nor email at the end, and leave "worker" empty as you have)

**Comment by QuentinHK0** [comment]
Hi NanMetal, 
I will do a test today, I will keep you informed.

**Comment by QuentinHK0** [comment]
Wonderful! Everything works ! thanks a lot for your help and for your work !
https://i.imgur.com/sEXAeAD.jpg
